const API='https://three.ws/api/crypto/airdrops';
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
let registry=[];let filtered=[];let currentStatus='all';let watched=JSON.parse(localStorage.getItem('key404_airdrop_watch')||'[]');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=s=>String(s??'').toLowerCase().replace(/[_-]/g,' ');
function normalize(raw){
 const arr=Array.isArray(raw?.registry)?raw.registry:Array.isArray(raw?.opportunities)?raw.opportunities:Array.isArray(raw)?raw:[];
 return arr.map((x,i)=>({
  id:x.id||x.slug||('airdrop-'+i),name:x.name||x.project_name||x.title||'Unnamed project',chain:x.chain||x.blockchain||(Array.isArray(x.blockchains)?x.blockchains.join(', '):'Unknown'),status:norm(x.status||'unknown'),score:Number.isFinite(Number(x.score))?Number(x.score):null,eligibility:x.eligibility||null,estimatedValue:x.estimatedValue||x.estimated_value||null,deadline:x.deadline||x.end_date||null,source:x.source||x.link||x.url||null,description:x.description||'',categories:x.categories||x.category||[],met:x.met||[],missing:x.missing||[],manual:x.manual||[],updated:x.updated||x.updated_at||raw?.registryUpdated||null
 }));
}
function statusLabel(s){if(s.includes('claim'))return ['CLAIMABLE','green'];if(s.includes('active')||s.includes('ongoing')||s.includes('confirmed'))return ['ACTIVE','green'];if(s.includes('upcoming'))return ['UPCOMING','amber'];if(s.includes('ended')||s.includes('inactive'))return ['ENDED','red'];return [String(s||'UNKNOWN').toUpperCase(),'amber']}
function isWatched(id){return watched.includes(id)}
function saveWatch(){localStorage.setItem('key404_airdrop_watch',JSON.stringify(watched));$('#watchCount').textContent=watched.length}
function toggleWatch(id){if(isWatched(id))watched=watched.filter(x=>x!==id);else watched.push(id);saveWatch();render()}
function fmtDate(v){if(!v)return '—';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'})}
function scoreHtml(x){if(x.score==null)return '<span class="muted">Not scored</span>';return `<b>${x.score}/100</b><div class="bar"><i style="width:${Math.max(0,Math.min(100,x.score))}%"></i></div>`}
function card(x){const [sl,cl]=statusLabel(x.status);return `<article class="card"><div class="card-top"><div><div class="title">${esc(x.name)}</div><div class="chain">⛓ ${esc(x.chain)}</div></div><span class="badge ${cl}">${esc(sl)}</span></div><div class="meta"><div><small>ELIGIBILITY</small>${x.eligibility?`<b>${esc(String(x.eligibility).replace('_',' ').toUpperCase())}</b>`:'<b>REGISTRY ONLY</b>'}</div><div><small>DEADLINE</small><b>${esc(fmtDate(x.deadline))}</b></div><div><small>EST. VALUE</small><b>${esc(x.estimatedValue||'Not published')}</b></div><div><small>SCORE</small>${scoreHtml(x)}</div></div><div class="actions"><button onclick="details('${esc(x.id)}')">DETAILS</button><button onclick="toggleWatch('${esc(x.id)}')">${isWatched(x.id)?'★ WATCHING':'☆ WATCH'}</button>${x.source?`<a class="button" href="${esc(x.source)}" target="_blank" rel="noopener noreferrer">SOURCE ↗</a>`:''}</div></article>`}
function render(){
 const q=norm($('#search').value), chain=$('#chain').value, sort=$('#sort').value;
 filtered=registry.filter(x=>{const text=norm([x.name,x.chain,x.description,Array.isArray(x.categories)?x.categories.join(' '):x.categories].join(' '));if(q&&!text.includes(q))return false;if(chain!=='all'&&norm(x.chain)!==norm(chain))return false;if(currentStatus==='watched'&&!isWatched(x.id))return false;if(currentStatus!=='all'&&currentStatus!=='watched'){const s=norm(x.status);if(currentStatus==='active'&&!['active','ongoing','confirmed'].some(v=>s.includes(v)))return false;if(currentStatus==='claimable'&&!s.includes('claim'))return false;if(currentStatus==='upcoming'&&!s.includes('upcoming'))return false}return true});
 filtered.sort((a,b)=>{if(sort==='name')return a.name.localeCompare(b.name);if(sort==='score')return (b.score??-1)-(a.score??-1);if(sort==='deadline')return (new Date(a.deadline||'2999').getTime())-(new Date(b.deadline||'2999').getTime());return (new Date(b.updated||0).getTime())-(new Date(a.updated||0).getTime())});
 $('#list').innerHTML=filtered.length?filtered.map(card).join(''):'<div class="empty">NO LIVE RECORDS MATCH YOUR FILTER.<br><br>Try another chain, status or search term.</div>';
 $('#total').textContent=registry.length;$('#qualified').textContent=registry.filter(x=>x.eligibility==='qualified').length;$('#progress').textContent=registry.filter(x=>x.eligibility==='in_progress').length;saveWatch();
}
function buildChains(){const chains=[...new Set(registry.map(x=>x.chain).filter(Boolean))].sort();$('#chain').innerHTML='<option value="all">ALL CHAINS</option>'+chains.map(c=>`<option value="${esc(c)}">${esc(c.toUpperCase())}</option>`).join('')}
async function load(){
 $('#apiState').className='status offline';$('#apiState').textContent='● CONNECTING';$('#notice').classList.add('hidden');$('#list').innerHTML='<div class="empty">CONNECTING TO LIVE AIRDROP REGISTRY...</div>';
 try{const r=await fetch(API,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();registry=normalize(data);if(!registry.length)throw new Error('The live registry returned no records.');buildChains();$('#apiState').className='status online';$('#apiState').textContent='● LIVE';$('#lastRefresh').textContent=new Date().toLocaleTimeString();render()}catch(e){registry=[];$('#apiState').className='status offline';$('#apiState').textContent='● ERROR';$('#notice').textContent='LIVE DATA ERROR: '+e.message+' — No mock data is shown. Retry when the upstream registry is available.';$('#notice').classList.remove('hidden');$('#list').innerHTML='<div class="empty">LIVE AIRDROP DATA UNAVAILABLE.<br><br>Nothing has been fabricated or cached as fake data.</div>';$('#total').textContent='—';$('#qualified').textContent='—';$('#progress').textContent='—'}}
function details(id){const x=registry.find(a=>a.id===id);if(!x)return;const [sl,cl]=statusLabel(x.status);$('#detail').innerHTML=`<div class="detail"><div class="eyebrow">LIVE REGISTRY RECORD</div><h2>${esc(x.name)}</h2><p><span class="badge ${cl}">${esc(sl)}</span> &nbsp; <span class="muted">${esc(x.chain)}</span></p><div class="meta"><div><small>SCORE</small><b>${x.score==null?'Not scored':x.score+'/100'}</b></div><div><small>ELIGIBILITY</small><b>${esc(x.eligibility||'Registry only')}</b></div><div><small>DEADLINE</small><b>${esc(fmtDate(x.deadline))}</b></div><div><small>EST. VALUE</small><b>${esc(x.estimatedValue||'Not published')}</b></div></div><p>${esc(x.description||'No description published by the registry.')}</p>${x.met.length?`<h3>✓ MET</h3><ul class="detail-list">${x.met.map(v=>`<li>${esc(v.description||v)}</li>`).join('')}</ul>`:''}${x.missing.length?`<h3>△ MISSING</h3><ul class="detail-list">${x.missing.map(v=>`<li>${esc(v.description||v)}</li>`).join('')}</ul>`:''}${x.manual.length?`<h3>MANUAL STEPS</h3><ul class="detail-list">${x.manual.map(v=>`<li>${esc(v.description||v)}</li>`).join('')}</ul>`:''}<p class="muted">Registry updated: ${esc(x.updated||'—')}</p>${x.source?`<a href="${esc(x.source)}" target="_blank" rel="noopener noreferrer">OPEN PUBLISHED SOURCE ↗</a>`:''}</div>`;$('#modal').classList.remove('hidden')}
window.details=details;window.toggleWatch=toggleWatch;
$$('.tabs button').forEach(b=>b.addEventListener('click',()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentStatus=b.dataset.status;render()}));
$('#search').addEventListener('input',render);$('#chain').addEventListener('change',render);$('#sort').addEventListener('change',render);$('#refresh').addEventListener('click',load);$('#close').addEventListener('click',()=>$('#modal').classList.add('hidden'));$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')});
function clock(){$('#clock').textContent=new Date().toLocaleTimeString('en-GB')+' LOCAL'}setInterval(clock,1000);clock();saveWatch();let p=0;const boot=setInterval(()=>{p+=20;$('#pct').textContent=p+'%';if(p>=100){clearInterval(boot);$('#boot').classList.add('hidden');$('#app').classList.remove('hidden');load()}},140);
