const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
const airdrops=[['ZKDROP','Ethereum / ZK','Snapshot: Oct 12','HOT'],['HOODNET','Robinhood Chain','Tasks active','LIVE'],['ARCX','Arc','Claim: Oct 19','HOT'],['SOLVAULT','Solana','Season 2 farming','LIVE'],['BASEBOX','Base','Eligibility open','LIVE'],['VOID404','EVM','Coming soon','SOON']];
const testnets=[['Robinhood Chain','5 tasks','ACTIVE'],['Arc Testnet','3 tasks','ACTIVE'],['Base Sepolia','7 tasks','ACTIVE'],['Monad Testnet','4 tasks','ACTIVE'],['Sui Testnet','2 tasks','ACTIVE']];
const quests=[['Daily Wallet Check','Connect wallet + verify activity','+10 XP'],['Testnet Runner','Complete 3 testnet interactions','+50 XP'],['Airdrop Hunter','Track 5 campaigns','+25 XP'],['Contract Detective','Scan a contract','+15 XP'],['NFT Collector','Hold or mint an NFT','+20 XP']];
const activity=[['09:42','0x8a...31f2','SWAP','0.12 ETH'],['08:16','0x8a...31f2','NFT MINT','1 NFT'],['YESTERDAY','0x8a...31f2','APPROVE','USDC'],['SEP 28','0x8a...31f2','TRANSFER','0.03 ETH']];
const calendar=[['OCT 02','HOODNET','Quest checkpoint'],['OCT 05','ZKDROP','Eligibility update'],['OCT 12','ZKDROP','Snapshot'],['OCT 19','ARCX','Claim window'],['OCT 24','SOLVAULT','Season closes']];
function render(){ $('#airdropCards').innerHTML=airdrops.map(x=>`<div class="panel"><h2>${x[0]}</h2><div class="muted">${x[1]}</div><p>${x[2]}</p><span class="tag ${x[3]=='HOT'?'hot':'safe'}">${x[3]}</span></div>`).join('');$('#testnetList').innerHTML=testnets.map(x=>`<div class=item><span><b>${x[0]}</b><br><small class=muted>${x[1]}</small></span><span class="tag safe">${x[2]}</span></div>`).join('');$('#questList').innerHTML=quests.map((x,i)=>`<div class=item><span><b>${x[0]}</b><br><small class=muted>${x[1]}</small></span><button onclick="completeQuest(${i})">${x[2]}</button></div>`).join('');$('#activityList').innerHTML=activity.map(x=>`<div class=item><span>${x[0]}<br><small class=muted>${x[1]}</small></span><span>${x[2]}<br><b>${x[3]}</b></span></div>`).join('');$('#calendarList').innerHTML=calendar.map(x=>`<div class=item><span><b>${x[0]}</b> — ${x[1]}</span><span class=tag>${x[2]}</span></div>`).join('')}
function show(id){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+id).classList.add('active');$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'});log('opened '+id+' module')}
$$('#nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));function log(x){$('#log').innerHTML+=`<div>> ${x}</div>`;$('#log').scrollTop=99999}function notify(x){let t=$('#toast');t.textContent=x;t.style.display='block';setTimeout(()=>t.style.display='none',2600)}
function connectDemo(){localStorage.setItem('key404Connected','1');$('#access').textContent='KEY HOLDER';$('#walletStatus').textContent='0x8a7F...31f2 connected — demo wallet';log('wallet connected: 0x8a7F...31f2');notify('Demo wallet connected');show('wallet')}
function checkEligibility(){let v=$('#walletInput').value.trim();if(!v)return notify('Enter a wallet address first.');let ok=v.length>20;$('#eligibility').innerHTML=ok?`<b style="color:var(--green)">ELIGIBILITY CHECK COMPLETE</b><br><br>Wallet: ${v.slice(0,12)}...<br>Matched campaigns: <b>4</b><br>Potential status: <span class="tag safe">ELIGIBLE</span>`:`<b style="color:var(--red)">INVALID INPUT</b><br>Use a valid wallet address.`;log('eligibility scan completed')}
function scanContract(){let v=$('#contractInput').value.trim();if(!v)return notify('Paste a contract address.');$('#scanResult').innerHTML=`<b>CONTRACT FOUND</b><br><br>Type: ERC-20 / NFT compatible<br>Network: EVM<br>Proxy: Unknown<br>Source verification: Check explorer<br>Risk signals: <span class="tag safe">NO BASIC RED FLAGS</span><br><small class="muted">Demo heuristic — verify independently before interacting.</small>`;log('contract scan completed')}
function riskCheck(){let v=$('#riskInput').value.trim();if(!v)return notify('Paste a contract address.');$('#riskResult').innerHTML=`<b>RISK SCREEN COMPLETE</b><br><br>Ownership: UNKNOWN<br>Liquidity: UNKNOWN<br>Mint controls: UNKNOWN<br>Blacklist controls: UNKNOWN<br>Honeypot simulation: NOT RUN<br><br><span class="tag hot">MANUAL REVIEW REQUIRED</span>`;log('risk screen completed')}
function completeQuest(i){let score=Number(localStorage.getItem('key404score')||742)+[10,50,25,15,20][i];localStorage.setItem('key404score',score);$('#score').textContent=score;notify('Quest completed — XP added');log('quest completed: '+quests[i][0])}
function tick(){let d=new Date();$('#clock').textContent=d.toLocaleTimeString('en-GB')+' UTC'+(d.getTimezoneOffset()>0?'-':'+')+Math.abs(d.getTimezoneOffset()/60)}
let p=0;let boot=setInterval(()=>{p+=20;$('#bootpct').textContent=p+'%';if(p>=100){clearInterval(boot);setTimeout(()=>{$('#boot').classList.add('hidden');$('#app').classList.remove('hidden')},300)}},160);render();setInterval(tick,1000);tick();if(localStorage.getItem('key404Connected'))$('#access').textContent='KEY HOLDER';
